<?php
/**
 * @file
 * Hook functions for Patterns integration
 */

function d2d_patterns($data = NULL){
	
	$tags['d2d_public_key'] = array(
    PATTERNS_INFO   => t('Create/Modify/Delete the value pair public key - instance'),
    PATTERNS_CREATE => array('d2d_patterns_insert_public_keys'),
    PATTERNS_MODIFY => array('d2d_patterns_update_public_keys'),
    PATTERNS_DELETE => array('d2d_patterns_delete_public_keys'),
    PATTERNS_EXPORT => array(
                          PATTERNS_EXPORT_ALL => 'd2d_patterns_export_all_public_keys',
                        ),
  );
  
  $tags['d2d_own_keys'] = array(
    PATTERNS_INFO   => t('Create/Modify/Delete public and or private key for the own instance. Must be called after a D2D id is set.'),
    PATTERNS_CREATE => array('d2d_patterns_insert_own_keys'),
    PATTERNS_MODIFY => array('d2d_patterns_insert_own_keys'),
    PATTERNS_DELETE => array('d2d_patterns_delete_own_keys'),
    PATTERNS_EXPORT => array(
                          PATTERNS_EXPORT_ALL => 'd2d_patterns_export_own_keys',
                          'Only the public key' => 'd2d_patterns_export_own_public_key',
                        ),
  );
  
  $tags['d2d_friendship'] = array(
    PATTERNS_INFO   => t('Create/Modify/Delete Taxonomy Vocabularies'),
    PATTERNS_CREATE => array('taxonomy_form_vocabulary'),
    PATTERNS_MODIFY => array('taxonomy_form_vocabulary'),
    PATTERNS_DELETE => array('taxonomy_vocabulary_confirm_delete'),
    PATTERNS_FILES  => array('modules/taxonomy/taxonomy.admin.inc'),
    PATTERNS_EXPORT => array(
                          PATTERNS_EXPORT_ALL => 'taxonomy_patterns_export_all_vocs',
                        ),
  );
  
  $tags['d2d_group'] = array(
    PATTERNS_INFO   => t('Create/Modify/Delete Taxonomy Vocabularies'),
    PATTERNS_CREATE => array('taxonomy_form_vocabulary'),
    PATTERNS_MODIFY => array('taxonomy_form_vocabulary'),
    PATTERNS_DELETE => array('taxonomy_vocabulary_confirm_delete'),
    PATTERNS_FILES  => array('modules/taxonomy/taxonomy.admin.inc'),
    PATTERNS_EXPORT => array(
                          PATTERNS_EXPORT_ALL => 'taxonomy_patterns_export_all_vocs',
                        ),
  );
  
  $tags['d2d_permission'] = array(
		PATTERNS_INFO   => t('Create/Modify/Delete Taxonomy Vocabularies'),
	  PATTERNS_CREATE => array('taxonomy_form_vocabulary'),
	  PATTERNS_MODIFY => array('taxonomy_form_vocabulary'),
	  PATTERNS_DELETE => array('taxonomy_vocabulary_confirm_delete'),
	  PATTERNS_FILES  => array('modules/taxonomy/taxonomy.admin.inc'),
	  PATTERNS_EXPORT => array(
	                          PATTERNS_EXPORT_ALL => 'taxonomy_patterns_export_all_vocs',
                        ),
  );
  
  
  return $tags;
  
}

function d2d_patterns_insert_own_keys($form_id, $form_state) {
	if (isset($form_state['values']['d2d_own_keys']['public'])) {
		d2d_api_own_public_key_set($form_state['values']['d2d_own_keys']['public']);
	}
	if (isset($form_state['values']['d2d_own_keys']['private'])) {
		d2d_api_own_private_key_set($form_state['values']['d2d_own_keys']['private']);
	}
}

function d2d_patterns_delete_own_keys($form_id, $form_state) {
	if (isset($form_state['values']['d2d_own_keys']['public'])) {
		d2d_api_own_public_key_del($form_state['values']['d2d_own_keys']['public']);
	}
	if (isset($form_state['values']['d2d_own_keys']['private'])) {
		d2d_api_own_private_key_del($form_state['values']['d2d_own_keys']['private']);
	}
}

function d2d_patterns_export_own_keys($args = NULL, &$result = NULL) {
	$actions = array();
	$action_type = PATTERNS_MODIFY; // pre-init 
	
	if (isset($args['type']) && $args['type'] == PATTERNS_CREATE) {
  	$action_type = PATTERNS_CREATE;
	}
	
	$keys = array($action_type => array(
		'tag' => 'd2d_own_keys',
		'public' => d2d_api_own_public_key_get(),
		'private' => d2d_api_own_private_key_get(),
	));
  
  return $keys;
}



function d2d_patterns_export_own_public_key($args = NULL, &$result = NULL) {
	$actions = array();
	$action_type = PATTERNS_MODIFY; // pre-init 
	
	if (isset($args['type']) && $args['type'] == PATTERNS_CREATE) {
  	$action_type = PATTERNS_CREATE;
	}
	
	$keys = array($action_type => array(
		'tag' => 'd2d_own_keys',
		'public' => d2d_api_own_public_key_get(),
	));
  
  return $keys;
}

function d2d_patterns_export_all_public_keys($args = NULL, &$result = NULL) {
	$actions = array();
	$action_type = PATTERNS_MODIFY; // pre-init 
	
	if (isset($args['type']) && $args['type'] == PATTERNS_CREATE) {
  	$action_type = PATTERNS_CREATE;
	}
	
  $keys = d2d_api_public_key_get_array();
  
  foreach ($keys as $k) {
  	$action = array($action_type => array('tag' => 'd2d_public_key', 'd2d_id' => $k['d2d_id'], 'public_key' => $k['public_key']));
  	if ($action_type == PATTERNS_MODIFY) {
  		$action[$action_type]['id'] = $k['id'];
  	}
  	array_push($actions, $action);
  }
  return $actions;
}


function d2d_patterns_insert_public_keys($form_id, $form_state) {
	$d2d_id = $form_state['values']['d2d_id'];
	$public_key = $form_state['values']['public_key'];
	d2d_api_public_key_set($d2d_id, $public_key);
}

function d2d_patterns_update_public_keys($form_id, $form_state) {
	$update = array();
	if (isset($form_state['values']['d2d_id'])) {
		$keys = d2d_api_public_key_get($form_state['values']['d2d_id']);
		$update['instance_id'] = $keys[0]->id;
	}
	if (isset($form_state['values']['public_key'])) {
		$update['public_key'] = $form_state['values']['public_key'];
	} 
	d2d_api_public_key_update($form_state['values']['id'], $update);
}

function d2d_patterns_delete_public_keys($form_id, $form_state) {
	if (!isset($form_state['values']['id'])) {
		$id = d2d_api_public_key_return_id($form_state['values']['d2d_id'], $form_state['values']['public_key']);
	}
	else {
		$id = $form_state['values']['id'];
	}
	d2d_api_public_key_delete($id);
}

// Validate the values for an action before running the pattern
function d2d_patterns_validate($action, $tag, &$data) {
 	$result = array();
  $status = PATTERNS_SUCCESS;
  $msg = '';
  
  // SYNTACTIC VALIDATION
  
  if ($tag == 'd2d_public_key') {
  	
  	if ($action == PATTERNS_CREATE) {
	  	$kcheck = patterns_utils_key_exists(array('public_key', 'd2d_id'), $data);
	  	  		
	  	// It is sufficient to have either vid or machine_name
	  	if (!($kcheck['public_key'] || $kcheck['d2d_id'])) {
	  	
		  	$msg = t("The following mandatory keys are missing: ");
		  	foreach ($kcheck as $key => $exist) {
					if (!$exist) {
						$status = PATTERNS_ERR;
						$msg .= $key . ', ';
					} 
		  	}
	  		$msg = substr($msg, 0, -2);
	  	}
  	}
  	
  	if ($action == PATTERNS_MODIFY) {  
  		$kcheck = patterns_utils_key_exists(array('public_key', 'd2d_id', 'id'), $data);
  			
  		if (!$kcheck['id']) {
  			$msg = t("The 'id' attribute is required.");
  			$status = PATTERNS_ERR;
  		}
  		else if (!($kcheck['public_key'] && $kcheck['d2d_id'])) {
  			$msg = t("Either the 'public_key' or the 'd2d_id' attributes or both are required");
  			$status = PATTERNS_ERR;
  		}
  	}
  	
  	else { // PATTERNS_DELETE
  		$kcheck = patterns_utils_key_exists(array('public_key', 'd2d_id', 'id'), $data);
  		
  		// Either the id or the combination d2d_id public_key
  		if (!$kcheck['id'] && !($kcheck['public_key'] && $kcheck['d2d_id'])) {

  			$msg = t("Either the 'id' attribute or the combination 'public_key' and 'd2d_id' is required");
  			$status = PATTERNS_ERR;
  		}
  		
  	}
  }
  
  if ($status == PATTERNS_ERR) {
  	return patterns_results($status, $msg);	
  }
  
  // SEMANTIC VALIDATION
  
  if ($tag == 'd2d_public_key') {
  	$d2d_id = @$data['d2d_id'];
  	$public_key = @$data['public_key'];
  	$public_key_short =  '...' . @d2d_substr_public_key($public_key);
  	
  	$keys = @d2d_api_public_key_get_array($d2d_id);
  	
  	if ($action == PATTERNS_CREATE) {  
  		
  		$instance = d2d_api_instance_get($d2d_id);

  		if ($instance === FALSE) {
  			$result[] = array(PATTERNS_WARNING_ELEMENT_UNDEFINED => 
        	t('No instance associated with key %k found.', array('%k' => $data['d2d_id'],)));
  		}
  		else if (d2d_api_public_key_exist($d2d_id, $public_key)) {
				$result[] = array(PATTERNS_WARNING_ALREADY_DEFINED_ELEMENT => 
        	t('Instance %i has already public key %k.', array('%i' => $d2d_id, '%k' => $public_key_short,)));
  		}
  	}
  	
  	else if ($action == PATTERNS_MODIFY) {  
  		$id = $data['id'];
  		// modify by id	
  		$key = d2d_api_public_key_get_by_id($id);
  			
  		if (empty($key)) {
  			$result[] = array(PATTERNS_WARNING_ELEMENT_UNDEFINED => 
        	t('No public key to modify with \'id\' :id', array(':id' => $id,)));
  		}	
  	}	
  	
  	else { // PATTERS_DELETE
  		// delete by id	
  		if (isset($data['id'])) {
  			$id = $data['id'];
  			$key = d2d_api_public_key_get_by_id($id);
  			
  			if (empty($key)) {
  				$result[] = array(PATTERNS_WARNING_ELEMENT_UNDEFINED => 
        		t('No public key to modify with \'id\' :id', array(':id' => $id,)));
  			}	
  		}
  		// pub_key and d2d_id are set
  		else if (!d2d_api_public_key_exist($d2d_id, $public_key)) { 
  			$result[] = array(PATTERNS_WARNING_ELEMENT_UNDEFINED => 
        		t('The pair instance-public key (%i-%k) was not found.', array('%i' => $d2d_id, '%k' => $public_key_short,)));
  		}	
  	}
  	
  }
  	
  return patterns_results($status, $msg, $result);	
   
}